CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64),
  email VARCHAR(64),
  hash  VARCHAR(128)
);

CREATE TABLE Event (
  id SERIAL PRIMARY KEY,
  startDate TIMESTAMP,
  endDate TIMESTAMP,
  ownerID SERIAL NOT NULL,
  title VARCHAR(64),
  comment TEXT,

  FOREIGN KEY (ownerID) REFERENCES Users(id)
);

CREATE TABLE Shared (
  userID SERIAL NOT NULL,
  eventID SERIAL NOT NULL,

  FOREIGN KEY (userID) REFERENCES Users(id),
  FOREIGN KEY (eventID) REFERENCES Event(id)
);
